#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "SelfTest.h"

SpandexAudioProcessor::SpandexAudioProcessor()
    : AudioProcessor(BusesProperties()
                          .withInput("Input", juce::AudioChannelSet::stereo(), true)
                          .withOutput("Output", juce::AudioChannelSet::stereo(), true))
{
}

SpandexAudioProcessor::~SpandexAudioProcessor() = default;

const juce::String SpandexAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

void SpandexAudioProcessor::prepareToPlay(double sampleRate, int samplesPerBlockExpected)
{
    audioEngine.prepareToPlay(sampleRate, samplesPerBlockExpected);
}

void SpandexAudioProcessor::releaseResources()
{
    audioEngine.releaseResources();
}

bool SpandexAudioProcessor::isBusesLayoutSupported(const BusesLayout& layouts) const
{
    // Accepting a (currently unused) stereo input bus - in addition to
    // disabled/no input - is what lets a host treat this as droppable on a
    // regular audio track, not just an instrument/MIDI track.
    return layouts.getMainOutputChannelSet() == juce::AudioChannelSet::stereo()
        && (layouts.getMainInputChannelSet() == juce::AudioChannelSet::stereo()
            || layouts.getMainInputChannelSet().isDisabled());
}

void SpandexAudioProcessor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer&)
{
    juce::ScopedNoDenormals noDenormals;
    // This is a self-contained player/processor (load a file, play it
    // through the pitch/warp/FX chain), not an insert effect - whatever's
    // already in the buffer (an audio track's own signal, if this is placed
    // on one) is discarded; the output is filled entirely from the internal
    // engine.
    audioEngine.renderNextBlock(buffer, buffer.getNumSamples());
}

juce::AudioProcessorEditor* SpandexAudioProcessor::createEditor()
{
    return new SpandexAudioProcessorEditor(*this);
}

// Every JUCE plugin project must define this factory - called once by
// whichever wrapper (VST3 host, or JUCE's own Standalone app shell) is
// hosting the plugin, to obtain the AudioProcessor instance.
//
// The old Standalone-only build intercepted `--selftest <in.wav> <outDir>`
// in JUCEApplication::initialise() before any window opened. There's no
// equivalent hook once the Standalone build is generated by JUCE's plugin
// client (juce_add_plugin), so the interception moves here instead - it's
// the earliest point every format's startup path funnels through, and
// checking argv is harmless for a real VST3 host (its own command line
// will never match).
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    static std::unique_ptr<juce::FileLogger> pluginLogger;
    if (juce::Logger::getCurrentLogger() == nullptr)
    {
        pluginLogger.reset(juce::FileLogger::createDefaultAppLogger("SPANDEX", "log.txt", "SPANDEX started"));
        juce::Logger::setCurrentLogger(pluginLogger.get());
    }

    auto args = juce::JUCEApplicationBase::getCommandLineParameterArray();
    if (args.size() >= 3 && args[0] == "--selftest")
    {
        runSelfTest(juce::File(args[1]), juce::File(args[2]));
        std::exit(0);
    }

    return new SpandexAudioProcessor();
}
